# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2045967d1228bbdc1671ef4b3882ef7e9650057d57b823ffd3decd43e35b96d40bbe7173b5a91f07c1c0ad49b5d77142c7a528a279f202e0c72907cac5712b56

test:
  secret_key_base: 40650414f1c652a615f038ea2ec9b9309bba25ac744090e4f3ecff5e9ea675b3f285abe7ba6ddf947c3c1021352bb46df71e8db145506595057e4a7bb068fb08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
